# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e36908ab553164173b0523f5dfdf69a2"
name = "MMC"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
